language: python
sudo: required
services:
  - docker
cache: pip
os:
  - linux
python:
  - "3.6"
script:
  - pip install -r requirements/prod.txt
  - pip install -r requirements/test.txt
  - nose2 --with-coverage
after_success:
  - pip install pylint pydocstyle mypy
  - ./lintstats.sh
  - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD";
    docker build . -t arxiv/search arxiv/search:${TRAVIS_COMMIT};
    docker push arxiv/search:${TRAVIS_COMMIT}
  - coveralls
