# Provides local instances of collaborating services for testing the
# indexing agent.
#
# - Localstack (provides Kinesis, DynamoDB).
# - Elasticsearch.
# - Metadata: stub for docmeta service (see ../Dockerfile-metadata).
---
version: '3'

services:
  search-test-elasticsearch:
    build:
      context: ../
      dockerfile: Dockerfile-elasticsearch
    container_name: search-test-elasticsearch
    environment:
      http.host: '0.0.0.0'
      transport.host: '127.0.0.1'
    ports:
      - "9202:9200"
      - "9300:9300"
    networks:
      - search-test

  search-metadata:
    build:
      context: ../
      dockerfile: Dockerfile-metadata
    container_name: search-metadata
    environment:
      LOGLEVEL: 10
    networks:
      - search-test

  search-agent:
    build:
      context: ../
      dockerfile: Dockerfile-agent
    container_name: search-agent
    environment:
      AWS_ACCESS_KEY_ID: "foo"
      AWS_SECRET_ACCESS_KEY: "bar"
      CLOUDWATCH_ENDPOINT: "https://search-test-localstack:4582"
      DYNAMODB_ENDPOINT: "https://search-test-localstack:4569"
      KINESIS_ENDPOINT: "https://search-test-localstack:4568"
      METADATA_ENDPOINT: "http://search-metadata:8000/docmeta/"
      ELASTICSEARCH_SERVICE_HOST: "search-test-elasticsearch"
      ELASTICSEARCH_SERVICE_PORT: "9200"
      ELASTICSEARCH_PORT_9200_PROTO: "http"
      ELASTICSEARCH_USER: ""
      ELASTICSEARCH_PASSWORD: ""
      ELASTICSEARCH_VERIFY: "false"
      KINESIS_VERIFY: "false"
      DYNAMODB_VERIFY: "false"
      CLOUDWATCH_VERIFY: "false"
      LOGLEVEL: 10
      LOGFILE: "/var/log/search-agent-processor.log"
      MODE: "test"
      JAVA_FLAGS: "-Dcom.amazonaws.sdk.disableCertChecking"
      AWS_CBOR_DISABLE: "true"
      AGENT_CHECKPOINT_FREQ: "1"
      AGENT_SLEEP_SECONDS: "1"
    networks:
      - search-test
    depends_on:
      - search-test-localstack
      - search-test-elasticsearch
      - search-metadata

  search-test-localstack:
    image: atlassianlabs/localstack
    container_name: search-test-localstack
    networks:
      - search-test
    ports:
      - "5582:4582"
      - "5568:4568"
      - "5569:4569"
    environment:
      USE_SSL: 'true'
      DEBUG: 'true'

networks:
  search-test:
