openapi: "3.0.0"
info:
  version: "0.1"
  title: "arXiv Search API"
  description: "A RESTful API for arXiv documents."
  termsOfService: "https://arxiv.org/help/general",
  contact:
    name: "arXiv API Team"
    email: nextgen@arxiv.org
  license:
    name: MIT
servers:
  - url: https://arxiv.org/api
paths:
  /papers:
    get:
      operationId: queryPapers
      description: |
        Returns all published arXiv papers that respond to the specified
        query parameters. By default, returns most recent papers first.
      parameters:
        - name: primary_category
          in: query
          description: |
            Slug for the primary category or categories to which results
            should be limited.
          required: false
          style: form
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: All arXiv papers that respond to specified query.
          content:
            application/json:
              schema:
                $ref: '../schema/DocumentSet.json#DocumentSet'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /papers/{id}:
    get:
      description: Return metadata about an arXiv paper by arXiv ID.
      operationId: getPaperByID
      parameters:
        - name: id
          in: path
          description: arXiv ID of paper to retrieve.
          required: true
          schema:
            type: string
      response:
        '200':
          description: Metadata about the requested arXiv paper.
          content:
            application/json:
              schema:
                $ref: '../schema/Document.json#Document'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
